# Generated by Django 3.2.10 on 2022-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('pub_dt', models.DateTimeField()),
                ('img', models.ImageField(upload_to='media/')),
                ('body', models.TextField()),
            ],
        ),
    ]
