# Generated by Django 3.2.10 on 2022-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=255),
        ),
    ]
